defaults: &defaults
  identifier_template: 'ba.reeddeeddk'
  identifier_statefile: '/tmp/oubliette-minter-state'
  notification_email_from: 'oubliette@example.com'
  notification_email_to: []
  fits_path: '/home/qgkb58/hydra/fits-0.8.6/fits.sh'

development:
  <<: *defaults
  ingestion_path: ['/tmp/','/home/qgkb58/hydra/testdata']

test:
  <<: *defaults

production:
  <<: *defaults
